### ISSUE TITLE
Broken build after switching to goreleaser

### ISSUE THREAD

**Issue by baniol** [heptio/authenticator#48]
I was trying to build images on the latest `v0.2.0-pre` tag. However, running `make build` seems to result in incomplete images - I wasn't able to run the `server` command, for instance.
Changing `main: ./cmd/heptio-authenticator-aws/root.go` to `main: ./cmd/heptio-authenticator-aws/` in the `.goreleaser.yaml` file fixed the issue.

**Comment by mumoshu** [comment]
@baniol Thx! You saved my day, and I've just submitted a PR for the fix #59
