### ISSUE TITLE
Feature request: Option to not create a webhook kubeconfig

### ISSUE THREAD

**Issue by mumoshu** [heptio/authenticator#60]
We can use `heptio-authenticator-aws init` to pre-generate required files including the kubeconfig before running a server, rather than generating it at runtime of the server.

However, even in this case the server requires a needless write-access to the output dir to generate/write a new kubeconfig according to [here](https://github.com/heptio/authenticator/blob/b53aa08edf33917303e6583f84d6c555739f0bc5/pkg/server/server.go#L111).

Can we just introduce a command-line flag or a configuration key to turn off the automatic kubeconfig generation?

**Comment by nckturner** [comment]
Yeah this makes sense. Happy to merge if you submit a PR.
