### ISSUE TITLE
Support kubectl external credential provider

### ISSUE THREAD

**Issue by smelchior** [heptio/authenticator#64]
Hi,
we have integrated the heptio authenticator in our workflow and it has been working great. The Login process with kubectl is still a little complicated though. kubectl in kubernetes 1.10 added an interesting option for external auth providers https://github.com/kubernetes/features/issues/541
It would be great if the authenticator could support this.

Regards,
Sebastian

**Comment by nckturner** [comment]
Yeah, thanks for the issue.  It will be supported ASAP.
