### ISSUE TITLE
Authenticator Community Call (2018-04-05)

### ISSUE THREAD

**Issue by mattmoyer** [heptio/authenticator#66]
If you're reading this, you're invited to join our first Authenticator community call on Thursday, April 5th at [4pm Pacific Time](https://www.timeanddate.com/worldclock/converter.html?iso=20180405T230000&p1=1241&p2=179&p3=136&p4=37&p5=33&p6=248&p7=240). We'll talk about work in flight, pain points from active users, and discuss future changes.

### Links:
- [Calendar event](https://calendar.google.com/event?action=TEMPLATE&tmeid=MGhjOW1kcG1zZGJlNWtqOHRpNWc4cWZxdnEgaGVwdGlvLmNvbV80N2RyODVidGllcDIza280M2c5NjhncHZxa0Bn&tmsrc=heptio.com_47dr85btiep23ko43g968gpvqk%40group.calendar.google.com)
- [Zoom](https://zoom.us/j/538875715)
- [Agenda/notes](https://docs.google.com/document/d/18TQZFcnSl3wjvLkrsk5RwZh8YoXK1KwQptxxt7TIAes/edit)

**Comment by nckturner** [comment]
@mattmoyer thanks for setting up the call!

**Comment by mattmoyer** [comment]
Reminder that this is starting in a little over an hour from now.
