### ISSUE TITLE
Server metrics

### ISSUE THREAD

**Issue by mattmoyer** [heptio/authenticator#8]
The server should export metrics about the rate of authentication events and the latency of the STS validation requests.

**Comment by mattlandis** [comment]
I am going to take a look at adding metrics if none else has picked it up.   Do you have a preferred metrics library.  If not I'll get started with go-metrics.

**Comment by mattlandis** [comment]
@mattmoyer 
I have a PR ready for this using prometheus.  It is based on the PR for adding tests #37 so once that is merged I'll send it out.  Feel free to assign this to me.

**Comment by nckturner** [comment]
Closing this since we have first pass of metrics merged.
