### ISSUE TITLE
Heptio-authenticator dashboard example?

### ISSUE THREAD

**Issue by StevenACoffman** [heptio/authenticator#84]
So if I have a cluster configured to use the Heptio Authenticator, can I access the kubernetes dashboard using the token found like so:
`heptio-authenticator-aws token -i $CLUSTER_ID -r $ROLE_ARN`

I also see:
> You can also omit -r ROLE_ARN to sign the token with your existing credentials without assuming a dedicated role. This is useful if you want to authenticate as an IAM user directly or if you want to authenticate using an EC2 instance role or a federated role.

[On Securing the Kubernetes Dashboard](https://blog.heptio.com/on-securing-the-kubernetes-dashboard-16b09b1b7aca) details using the bitly oauth proxy via github. I'm looking for a heptio-authenticator AWS version.

**Comment by christopherhein** [comment]
Hey @StevenACoffman, yes, you can. It's a little strange first make sure you have `jq` installed then try this.

```bash
heptio-authenticator-aws token -i $CLUSTER_ID -r $ROLE_ARN | jq -r ".status.token"
```

then use the output as a token in the Dashboard. Let me know if that doesn't work.

**Comment by christopherhein** [comment]
Did that work for you? @StevenACoffman

**Comment by StevenACoffman** [comment]
Yes, it did! Thanks!

**Comment by mhobotpplnet** [comment]
Out of curiosity , is token valid for just 15 minutes?

**Comment by christopherhein** [comment]
Yes, @mhobotpplnet that is the standard lifetime of Signed STS Request, there was an old PR that tried to address this - https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/75 but needed to be revisited.

**Comment by okgolove** [comment]
Are there any news? It's really very annoying.
