### ISSUE TITLE
Feature request: Ship binaries with releases

### ISSUE THREAD

**Issue by lucaswilric** [heptio/authenticator#86]
I noticed that the [`Makefile`](https://github.com/heptio/authenticator/blob/master/Makefile) uses Goreleaser to build binaries for testing.

Are there particular obstacles or philosophical objections to including binaries in GitHub releases? My team and I would appreciate it greatly.

**Comment by christopherhein** [comment]
Thanks, @lucaswilric this is actually a dupe of https://github.com/heptio/authenticator/issues/76 we're still finalizing what our 1.10 release will actually be as well as this project is in progress to move to a SIG AWS owned repo.

**Comment by lucaswilric** [comment]
Thanks @christopherhein! In that case, I'll keep an eye on the two issues you've linked.
