### ISSUE TITLE
EKS heptio authentication using IAM without AWSCLI

### ISSUE THREAD

**Issue by softwarecoolie** [heptio/authenticator#89]
Hi , i followed getting started on aws EKS, and kubectl and this tool is all we need right? do i still need to set something on my box for AWS role?
 i get this 

`kubectl get all
could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
error: the server doesn't have a resource type "cronjobs"`

**Comment by softwarecoolie** [comment]
[https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html](url)

**Comment by nckturner** [comment]
@softwarecoolie to echo what @jrnt30 said, you should be able to use anything in the default aws credential chain, which includes the environment variables and config files.

**Comment by softwarecoolie** [comment]
Thank you @nckturner @jrnt30  , i was able to get it to working but missing the whole point... getting started EKS says no need of AWSCLI, proved the role etc info to heptio and it would authenticate for kubectl.. didnt work.. following worked
1. created user with EKS admin and added iam get role and iam pass role
2. created role with above user as trusted entity
3. in awscli credentials i had save access key and secret..  ( basically anyone who gets hold of my credentials they can have fun whatever crazy role setup i do on console) 

may be i am missing something!

**Comment by nckturner** [comment]
So the only things that matter in terms of authenticating to your cluster with kubectl are that your IAM identity that heptio authenticator is using is the same as the one that was used to create the cluster, and that your kubeconfig correctly specifies the cluster name, the endpoint, and the ca cert of the cluster.  Which user did you use to create the cluster?

**Comment by nckturner** [comment]
Sounds like you used a different user to create and access the cluster.  The cli is not required, but you do need aws credentials from your environment.  To add users, you will need to modify create and modify the config map as per the docs.

**Comment by hfern** [comment]
> To add users, you will need to modify create and modify the config map as per the docs.

@nckturner Can provide a URL to the docs?

**Comment by coconup** [comment]
For the least perspicacious such as myself, if you created the EKS cluster with an IAM **User** (with usename and pass) through the AWS console, you'll need to click on that user and hit "**Create access key**". The keys that are generated can then go into your `~/.aws/credentials` file in order for `kubectl` & co. to pick them up when doing things from the command line.

**Comment by dperic123** [comment]
Hi everyone,
I'm following the instructions here:https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html
But still get the issue above.
![image](https://user-images.githubusercontent.com/33552725/41852067-08f4ac5a-7858-11e8-9df4-649afe914dba.png)

**Comment by AKArunkumar** [comment]
` Warning  CleanupLoadBalancerFailed  <invalid> (x809 over 2d)  service-controller  Error cleaning up load balancer (will retry): error getting LB for service default/dev-clients-app-svc: NoCredentialProviders: no valid providers in chain. Deprecated.
           For verbose messaging see aws.Config.CredentialsChainVerboseErrors` <br>
is any one came across this bug?

**Comment by george-haddad** [comment]
So here's an interesting bit, I am getting the error mentioned in this issue, I created the EKS cluster while logged into the AWS console but not as a regular IAM User. I'm logged in via SSO SAML2.0 connection where my org is the identity provider. So essential my AWS account has no created users, just role `arns` so in that case how do I get this to work 😂

**Comment by george-haddad** [comment]
> So here's an interesting bit, I am getting the error mentioned in this issue, I created the EKS cluster while logged into the AWS console but not as a regular IAM User. I'm logged in via SSO SAML2.0 connection where my org is the identity provider. So essential my AWS account has no created users, just role `arns` so in that case how do I get this to work 😂

This resolved it [Edit trust relationship of user](https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-iam-policy-issues/)
