### ISSUE TITLE
Can't specify AWS CLI Profile

### ISSUE THREAD

**Issue by dansepp** [heptio/authenticator#93]
Executing commands using kubectl (AWS EKS specific version) or the heptio-authenticator-aws utilities returns the following error when the AWS CLI configure has not been run for the default profile:

"could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors"

Reference: https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html

Request: Provide a means to specify an AWS CLI profile (per the ~/.aws/config and ~/.aws/credentials files).

**Comment by jrnt30** [comment]
This is seemingly a duplicate.  Do any of the options listed in the link from https://github.com/heptio/authenticator/issues/89#issuecomment-395280764 work?

**Comment by christopherhein** [comment]
See this https://github.com/heptio/authenticator/issues/94#issuecomment-395565393 as well for how you could set this up

**Comment by dansepp** [comment]
Thank you both.  #94 is indeed a duplicate.
Adding the env: to my kubeconfig did the trick.

**Comment by AlexandrebQueiroz** [comment]
in my case, was a very simple mistake,
I had an credential.txt instead a credential. = (
